development:
  adapter: postgresql
  encoding: unicode
  database: postgres
  host: localhost
  pool: 5
  username: facebook
  password: test1

test:
  adapter: postgresql
  encoding: unicode
  database: postgres_test
  host: localhost
  pool: 5
  username: facebook
  password: test1